### ISSUE TITLE
Typo di Walkthrough Yudisium tahap 16

### ISSUE THREAD

**Issue by saputraiqbal** [filkomers/walkthrough-yudisium#2]
mohon dicek pada image yg menunjukkan kelengkapan pendaftaran yudisium yg hrs diserahkan kepada akademik lt 6. SC2-08 pada gambar seharusnya tertulis SC2-18. Terimakasih :)

Gambar Kelengkapan Pendaftaran Yudisium pada Walkthrough Yudisium : 
![1563754370720](https://user-images.githubusercontent.com/17638445/61599309-fab4eb80-ac51-11e9-9620-2b932c1daa4b.jpg)

Gambar Kelengkapan Pendaftaran Yudisium yang seharusnya (Sumber : Rikza Priyudha @ LINE): 
![S__45752323](https://user-images.githubusercontent.com/17638445/61599328-17512380-ac52-11e9-9f77-fbf920e0f4a3.jpg)

**Comment by azzamsa** [comment]
Hi Iqbal. 

Terima kasih telah berkontribusi.

Tetapi issue ini adalah duplikat dari #1.

Saya akan menutupnya untuk sementara waktu. Jangan ragu untuk membuka issue ini kembali, jika ada yang belum terselesaikan.
